services:
  backend:
    container_name: backend
    build:
      context: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/usr/app
    command: >
      sh -c "npm install &&
             npm run start:dev"
  frontend:
    container_name: frontend
    build:
      context: ./client
    volumes:
      - ./client:/usr/app
    ports:
      - 3000:3000
    depends_on:
      - backend
    command: >
      sh -c "npm install &&
             npm start"
  database:
    container_name: database    
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    logging:
      driver: none
volumes:
  mongodb:
